baseurl: 'https://services.m3o.com'
languageCode: 'en-us'
title: 'Micro Services'
themesDir: '../..'
theme: 'hugo-tania'
summaryLength: 10

params:
  titleEmoji: ''
  socialOptions:
    github:
    twitter:

menu:
  header:
    - name: Services
      url: '/services/'
  footer:
    - name: &copy; 2020 Micro Services, Inc.
      url: 'https://m3o.com'

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
